name: move_smart
description: Move Smart - Bus booking and trip tracking app for Rwanda.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.6
  bloc: ^8.1.4

  shared_preferences: ^2.3.2
  equatable: ^2.0.5
  get_it: ^8.0.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.7
  mockito: ^5.4.4
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
