// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFxyPePgusuEtaDSqAREZ3xsLxXfAgNg8',
    appId: '1:1080889566724:web:3b74e8fe261425402b3751',
    messagingSenderId: '1080889566724',
    projectId: 'move-smart-d317e',
    authDomain: 'move-smart-d317e.firebaseapp.com',
    storageBucket: 'move-smart-d317e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz5C5MGUdcHi-1EXHCBk-_uTP2cpCkuJE',
    appId: '1:1080889566724:android:a8d760660fb429142b3751',
    messagingSenderId: '1080889566724',
    projectId: 'move-smart-d317e',
    storageBucket: 'move-smart-d317e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU_cn819uF11neqaiIx5YhHz9a8ZRL6sY',
    appId: '1:1080889566724:ios:0bf884d084eb3bf72b3751',
    messagingSenderId: '1080889566724',
    projectId: 'move-smart-d317e',
    storageBucket: 'move-smart-d317e.firebasestorage.app',
    iosClientId: '1080889566724-eoi9e3s88qfijtg7ccq9qnhko4f3mq1v.apps.googleusercontent.com',
    iosBundleId: 'com.example.moveSmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU_cn819uF11neqaiIx5YhHz9a8ZRL6sY',
    appId: '1:1080889566724:ios:0bf884d084eb3bf72b3751',
    messagingSenderId: '1080889566724',
    projectId: 'move-smart-d317e',
    storageBucket: 'move-smart-d317e.firebasestorage.app',
    iosClientId: '1080889566724-eoi9e3s88qfijtg7ccq9qnhko4f3mq1v.apps.googleusercontent.com',
    iosBundleId: 'com.example.moveSmart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFxyPePgusuEtaDSqAREZ3xsLxXfAgNg8',
    appId: '1:1080889566724:web:e95cc3949e65c6ac2b3751',
    messagingSenderId: '1080889566724',
    projectId: 'move-smart-d317e',
    authDomain: 'move-smart-d317e.firebaseapp.com',
    storageBucket: 'move-smart-d317e.firebasestorage.app',
  );

}